spring:
  datasource:
    url: jdbc:mysql://192.168.169.128:3306/autotest?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    root: info
demo:
  say-what: hello..111er.
autotest:
  selenium:
    driver:
      chrome:
        platform-name: win10
